# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          academic
paginate:       5
baseurl:        /academic
url:            "https://j-faria.github.io/academic"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         João Faria
  url:          https://astro.up.pt/~jfaria
  email:        joao.faria@astro.up.pt

# Custom vars
version:        0.0.1
github:
  repo:         https://github.com/j-faria/academic

plugins:
  - jekyll-paginate
  - jekyll-gist


authors:
  joao:
    display: João Faria
    gravatar: 
    email: joao.faria@astro.up.pt
    web: https://astro.up.pt/~jfaria
    twitter: astroaware
    github: j-faria
  another:
    display: John Doe
    gravatar: 
    email: 
    web: 
    twitter: 
    github: 