repository: j-faria/webhome
permalink: /blog/:title
title: João Faria
paginate: 5
paginate_path: /blog/page:num
sass:
  sass_dir: _sass
  style: :compressed
future: true
markdown: kramdown
author:
  name: João Faria
  url: https://astro.up.pt/~jfaria
  email: joao.faria@astro.up.pt
version: 0.0.2
github:
  repo: https://github.com/j-faria/academic
plugins:
- jekyll-paginate
- jekyll-gist
- jekyll-github-metadata
authors:
  joao:
    display: João Faria
    gravatar: null
    email: joao.faria@astro.up.pt
    web: https://astro.up.pt/~jfaria
    twitter: astroaware
    github: j-faria
  another:
    display: John Doe
    gravatar: null
    email: null
    web: null
    twitter: null
    github: null

npapers: 71
